### PR TITLE
geant4-vmc: Add new versions

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
env/dev/fairroot_develop.yaml will pick this up.
Let's see.

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
@kresan 
Do we want the new geant4-vmc version for the next release in the `env/dev/` environments?
`fairroot@develop` seems to compile fine:
* https://cdash.gsi.de/testDetails.php?test=7003002&build=243337
* https://cdash.gsi.de/testDetails.php?test=7003020&build=243338
* https://cdash.gsi.de/testDetails.php?test=7003819&build=243346

Do you happen to know, whether a newer geant4 version is needed for this newer geant4-vmc?

**Comment by kresan** [comment]
This new geant4_vmc version should go into the next release, so let us include it in the dev environment.
Concerning the required geant4 version - no idea. We need to ask Ivana.

**Comment by kresan** [comment]
To my opinion, env/dev should contain latest releases of physics packages in compatible manner. This will allow testing on early basis.

**Comment by ChristianTackeGSI** [comment]
* @kresan Can you ask Ivana, please? So that we at least declare the needed versions in the spack recipe?
* Upgraded geant4-vmc from 5-0-p1 to 5-2 in `env/dev/sim*`
* Rebased

**Comment by ChristianTackeGSI** [comment]
Okay, CI works for adding those versions to `env/dev`.

So waiting for version info from Ivana.

**Comment by kresan** [comment]
According to Ivana, geant4_vmc 5.2 needs Geant4 10.6.x

**Comment by ChristianTackeGSI** [comment]
Okay, we have 10.06 in our repos. So that's fine.
I'll add the `depends_on()`.

**Comment by ChristianTackeGSI** [comment]
Oh wait, our `env/dev` still have geant4 10.05.p01. For a reason?

**Comment by kresan** [comment]
That was needed by the previous version of geant4_vmc

**Comment by ChristianTackeGSI** [comment]
Okay, this all goes down to `geant4-data` / `g4*` needing updates.

Either we update the whole chain, or leave geant4-vmc at 5-0-p1?

**Comment by kresan** [comment]
If I remember correctly, I have updated geant4-data to match geant4 10.06.

**Comment by kresan** [comment]
Yes, there is geant4-data@10.06 with proper depends_on

**Comment by ChristianTackeGSI** [comment]
Okay, does that look correct?
```python
    depends_on('geant4')
    depends_on('geant4@10.05:', when='@5-0:')
    depends_on('geant4@10.06:', when='@5-2:')
```

About geant4-data: Oh, you're right.

Okay, I'll update the envs. Let's see.

**Comment by kresan** [comment]
> Okay, does that look correct?
> 
> ```python
>     depends_on('geant4')
>     depends_on('geant4@10.05:', when='@5-0:')
>     depends_on('geant4@10.06:', when='@5-2:')
> ```

Yes, looks good

**Comment by dennisklein** [comment]
The timeouts will go away soon (when we switch to the dedicated machines)

**Review by dennisklein — APPROVED** [review]
Can you pls rebase once again, thx

**Pull request merged**
