### PR TITLE
[spack] dds: Add Version 3.6

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**

### CODE REVIEW

**Comment by AnarManafov** [comment]
@ChristianTackeGSI , I can't review/approve this patch to CMakeLists.txt.
It is similar to your patch FairRootGroup/DDS#354 As I mentioned on the PR, it doesn't work for me on OS X.
So, it's up to you to include this patch.

**Comment by ChristianTackeGSI** [comment]
Let's see, whether the patch works on our CI Mac.

**Comment by ChristianTackeGSI** [comment]
@AnarManafov The patch seems to work nicely on our OS X CI machine:
https://cdash.gsi.de/testDetails.php?test=10967707&build=318383

**Comment by AnarManafov** [comment]
@ChristianTackeGSI, I trust you, but I can't confirm.
How can I find the build logs? The link you sent doesn't have much info on it. It's not enough to see tests are ok, as I don't know what exactly they are testing.
I have to confirm that the build logs look expected.

**Comment by ChristianTackeGSI** [comment]
Build logs:
```console
…
*** Host .................: citmac001.gsi.de
*** Install tree .........: /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-453/build/install-tree
…
==> Installing dds
==> No binary for dds found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
==> dds: Executing phase: 'cmake'
==> dds: Executing phase: 'build'
==> dds: Executing phase: 'install'
[+] /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-453/build/install-tree/darwin-catalina-x86_64/apple-clang-12.0.0/dds-3.6-52fl7toq2txxy7nrjzmwuglwzzu5vnyu
```

```console
alfaci@citmac001 ~ % cd alfaci/workspace/FairRootGroup_FairSoft_PR-453/build/install-tree/darwin-catalina-x86_64/apple-clang-12.0.0/dds-3.6-52fl7toq2txxy7nrjzmwuglwzzu5vnyu
alfaci@citmac001 dds-3.6-52fl7toq2txxy7nrjzmwuglwzzu5vnyu % less -S .spack/spack-build-out.txt
```

**Comment by AnarManafov** [comment]
@ChristianTackeGSI , sorry to bother you. could you please attach the build log, at least the dds part?
I don't have account info for alfaci.

**Comment by AnarManafov** [comment]
@ChristianTackeGSI , I am afraid your patch gives the same error as the one you sent to DDS repo (OS X 12.1, cmake 3.22.1):
~~~
> make -j wn_bin 
....
[ 97%] Built target dds-agent
[100%] Generate WN binary package
CMake Error at /Users/anar/tmp/killme/DDS/cmake/DDSCollectWNPkgFiles.cmake:10 (file):
  file Resolved path is not absolute
~~~

I am not sure how exactly your build system skips this error.
I can't sign-off this change. If you urgently need to apply this patch nevertheless, please go ahead and approve it instead of me.

**Comment by ChristianTackeGSI** [comment]
@AnarManafov Can you try to track the build error down on your system?

Maybe add a debug message for `${WN_PKG_TARGETS}`?

**Comment by AnarManafov** [comment]
@ChristianTackeGSI , sure thing. Will do. It just will take some time. I have to finish something for alice pretty urgent. So, if the patch blocks you, go ahead and merge.

**Comment by ChristianTackeGSI** [comment]
It's not yet blocking FairSoft.

And even if we merged it as is, we can continue the analysis and tracking down of the issues in https://github.com/FairRootGroup/DDS/pull/354

**Comment by AnarManafov** [comment]
Agreed.

**Review by dennisklein — APPROVED** [review]

**Pull request merged**
