### PR TITLE
scripts: bump nanomsg to 0.8

### PR DESCRIPTION
**Pull request by sbinet**
please consider upgrading to nanomsg-0.8

### CODE REVIEW

**Comment by MohammadAlTurany** [comment]
Hallo Sebastien,
Could you please make the pull request to the dev and not to the master?
Thanks,
Mohammad

**Comment by sbinet** [comment]
done.

PTAL

**Comment by MohammadAlTurany** [comment]
Hallo,
It is still to the master, may you should close this one, rebase your branch to the dev and then make the pull request to the dev.
Thanks,
Mohammad

**Comment by sbinet** [comment]
I had my branch rebased onto `origin/dev` :

```
$ git l
* a5b81e9 (HEAD -> nanomsg-0.8, sbinet/nanomsg-0.8) all: bump nanomsg to 0.8
* c0be42a (sbinet/dev, origin/dev) Add FlatBuffers to external packages
* 0a22846 switch off the VC option in root only for power pc
* e17236d compiler in the config file has to be set by user
* 1ff74ee call autoreconf for nanomsg on ppc64
* 8bfc121 extra check for IBM ppc
* 4e397ba run on IBM test machines with PPC64
* 8fee618 (tag: nov15p3, sbinet/master, origin/master, origin/HEAD, master) Update version info.
```

but it seems github's PR is indeed stuck on master.

**Pull request closed without merging**
