### PR TITLE
fairroot: Run Unit Tests 18.2.1, 18.4.0, and develop

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
When we build and install the examples (+examples) we can run the unit tests (they're the combined with the examples) anyway too.

We run the unit tests for 18.2.1 and all newer versions.

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
# Current Snapshot of Issues
## Overview
* See: https://cdash.gsi.de/index.php?project=FairSoft&date=2020-05-06 (look for PR-238)
* The problems occur randomly, one can see that nicely on the distribution of errors there
* For example my desktop never showed an error

## Individual Builds
### Fedora30
* CDash: https://cdash.gsi.de/testDetails.php?test=6650900&build=235631
* `191227709 May  6 22:47 /lustre/rz/alfaci/workspace/FairRootGroup_FairSoft_PR-238/build/stage.tar.bz2`
* fairroot 18.2.1 / `8 - run_tutorial1_urqmd_TGeant3 (Failed)`
  * `Error in <TUnixSystem::FindDynamicLibrary>: libPythia6`
    Maybe related to https://github.com/FairRootGroup/FairRoot/issues/972
  *
        locf_() Warning: changing base from 7f8400000000 to 7f8300000000!!!
        This may result in program crash or incorrect results
         !!!!! ZFATAL called from MZSTOR
        1ZEBRA SYSTEM Post-Mortem from ZPOSTM.
        …
         *** Break *** segmentation violation

### GSI-Debian-8
* CDash: https://cdash.gsi.de/testDetails.php?test=6650915&build=235632
* `163474605 May  6 23:18 /lustre/rz/alfaci/workspace/FairRootGroup_FairSoft_PR-238@3/build/stage.tar.bz2`
* fairroot 18.2.1 / `46 - run_rutherford_TGeant3 (Failed)`
  * Errors much like above, just with a stack trace:

        zabend_ + 0x1a from libgeant321.so
        zfatal_ + 0x8f6 from libgeant321.so
        mzstor_ + 0x1950 from libgeant321.so
        g3zebra_ + 0xb7 from libgeant321.so
        g3cinit_ + 0x15 from libgeant321.so
        TGeant3::TGeant3(char const*, int) + 0x1c3 from libgeant321.so
        TGeant3TGeo::TGeant3TGeo(char const*, int) + 0x2c from libgeant321.so
        <unknown function>
        <unknown function>
        cling::Interpreter::RunFunction(…

### Ubuntu-18.04-LTS
* CDash: https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=235624
  fairroot 18.2.1 / `26 - MQ.ex-serialization1 (Timeout)`
  fairroot 18.2.1 / `27 - MQ.ex-serialization2 (Timeout)`
  fairroot 18.4.0 / `29 - ex_MQ_serialization1 (Timeout)`
  fairroot 18.4.0 / `30 - ex_MQ_serialization2 (Timeout)`
* `996913375 May  6 22:36 /lustre/rz/alfaci/workspace/FairRootGroup_FairSoft_PR-238@2/build/stage.tar.bz2`
* Most errors look quite alike:
```
Error in <TClonesArray::SetClass>: called with a null pointer
Error in <TTree::Bronch>: TClonesArray with no class defined in branch: MyHit
…
Warning in <TClass::Init>: no dictionary for class MyDigi is available
Warning in <TClass::Init>: no dictionary for class FairTimeStamp is available
Warning in <TClass::Init>: no dictionary for class FairMultiLinkedData_Interface is available
Warning in <TClass::Init>: no dictionary for class FairMultiLinkedData is available
Warning in <TClass::Init>: no dictionary for class FairLink is available
…
Error in <TMessage::CheckByteCount>: object of class TClonesArray read too few bytes: 8727 instead of 17417

 *** Break *** segmentation violation
 Generating stack trace...
<unknown> in libFairMQ.so.1.4
boost::detail::function::void_function_obj_invoker1<std::function<void (fair::mq::State)>, void, fair::mq::State>::invoke(boost::deta
boost::signals2::detail::signal_impl<void (fair::mq::State), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::
fair::mq::fsm::Machine_::ProcessWork()
fair::mq::StateMachine::ProcessWork()
fair::mq::DeviceRunner::Run()
main + 0xbc

**Comment by fuhlig1** [comment]
The errors

```
locf_() Warning: changing base from 7f8400000000 to 7f8300000000!!!
This may result in program crash or incorrect results
 !!!!! ZFATAL called from MZSTOR
1ZEBRA SYSTEM Post-Mortem from ZPOSTM.
```

are related to a feature of the Geant3 memory management. If I understood the problem correctly since Geant3 is a 32bit fortran program it can either run if the complete memory is below the 32bit boundary or above the boundary. If it gets a memory segment which crosses the boundary you get the shown error. If you would rerun the test you probably wouldn't see the error again. I Think the probability that a test fails with this error is around 1%.

**Comment by ChristianTackeGSI** [comment]
@fuhlig1
I think, those errors are bit more likely. They happened in the same run on two containers (Fedora and GSI-Debian-8).
That said, do you happen to know, whether there is an option to fix this?

**Comment by fuhlig1** [comment]
Don’t use Geant3. ;-}} 
The problem really is that Geant3 is a 32bit Fortran program that is run on a 64bit OS. I think we have to life with this problem. Maybe the problem occurs with containers more often than on bare metal.

**Comment by ChristianTackeGSI** [comment]
The next run is available in CDash here:
https://cdash.gsi.de/index.php?project=FairSoft&date=2020-05-09
(look at Nightly / dev_fairroot)

Basically, the errors are very comparable to my previous Snapshot, so I didn't work it out as elaborately this time.

The number of libPythia6 errors seems smaller, and maybe we need to rerun this to make sure, it's running with the current RC branch.

**Comment by ChristianTackeGSI** [comment]
Updated run here (look for `dev_fairroot`):
https://cdash.gsi.de/index.php?project=FairSoft&date=2020-07-13#Nightly

I'll look into the details tomorrow.

**Comment by rbx** [comment]
I could reproduce the error from the serialization example by running the test without running `config.sh` before it:

```
29: [ex-serialization1-processor][12:45:48][STATE][StateMachine.cxx:194:ProcessWork] INITIALIZING TASK ---> READY
29: [ex-serialization1-processor][12:45:48][STATE][StateMachine.cxx:194:ProcessWork] READY ---> RUNNING
29: [ex-serialization1-processor][12:45:48][INFO][FairMQDevice.cxx:487:RunWrapper] DEVICE: Running...
29: Warning in <TClass::Init>: no dictionary for class MyDigi is available
29: Warning in <TClass::Init>: no dictionary for class FairTimeStamp is available
29: Warning in <TClass::Init>: no dictionary for class FairMultiLinkedData_Interface is available
29: Warning in <TClass::Init>: no dictionary for class FairMultiLinkedData is available
29: Warning in <TClass::Init>: no dictionary for class FairLink is available
29: Error in <TClonesArray::SetClass>: called with a null pointer
29: Error in <TTree::Bronch>: TClonesArray with no class defined in branch: MyHit
```

After I call `config.sh` I get no errors even with `ctest -j8 -R "serialization*" -V --repeat-until-fail 100`.

So I think it is an environment problem.

**Comment by ChristianTackeGSI** [comment]
Well, in the spack recipe, we're just doing `make("test", parallel=False)`:
```console
==> [2020-07-14-00:04:10.616807] 'make' 'test'
Running tests...
/tmp/fairsoft_ctest.Gkfoa3/install-tree/linux-ubuntu18.04-zen/gcc-7.5.0/cmake-3.16.2-louvs2ys2lby2yimwh26gjpztfd7mvet/bin/ctest --force-new-ctest-process
```

So whatever environment setup is needed, should be done in cmake / ctest / test scripts.

**Comment by rbx** [comment]
Calling `config.sh` in the test script should solve the issue. Not sure if there is a better way of solving it meanwhile @dennisklein.

**Comment by ChristianTackeGSI** [comment]
We have mostly moved to workflow based testing in this area.
I left this branch alone for far too long.
I'll revisit sometime later and then create a fresh PR.

**Pull request closed without merging**
