### PR TITLE
[legacy] Multiple updates

### PR DESCRIPTION
**Pull request by dennisklein**
+ standalone `asio` package in preparation of upcoming `FairMQ` and `asiofi` releases

### CODE REVIEW

**Review by fuhlig1 — APPROVED** [review]

**Comment by dennisklein** [comment]
@fuhlig1 Should we also bump https://github.com/vmc-project/vgm/commits/v4-9 and https://pythia.org/history/ to latest?

**Comment by dennisklein** [comment]
The ODC bump does not build in this PR, but @AndreyLebedev is working on a fix directly in ODC, so switching this PR to draft until this is finished, so no package-level patch is required.

**Comment by AndreyLebedev** [comment]
@dennisklein The patch is in master now. Do you also need a new tag for ODC?

**Comment by dennisklein** [comment]
> @dennisklein The patch is in master now. Do you also need a new tag for ODC?

Thx, yes, tag would be good, but let's wait (I can test without a tag and only once everything looks good, it is worth tagging from my side. Of course, if you have other reasons in the meantime for a tag, don't wait on me).

**Comment by AndreyLebedev** [comment]
DDS is fixed now. The tag is the same.

**Comment by AndreyLebedev** [comment]
ODC is now `0.26`

**Pull request merged**
