### PR TITLE
[legacy] Bump Root version to 6.24.00

### PR DESCRIPTION
**Pull request by fuhlig1**

### CODE REVIEW

**Comment by fuhlig1** [comment]
I have tested the change locally on CentOS7 with the complete CbmRoot stack. All packages were compiled using C++17. Beside one failing test in CbmRoot all test have succeeded. Let's see which results the CI will deliver.

**Review by ChristianTackeGSI — APPROVED** [review]
Looks good to me. Even the checksum matches up with the spack recipe.

**Comment by dennisklein** [comment]
## [Fedora 33 - `root-configure.log`](https://alfa-ci.gsi.de/job/FairRootGroup/job/FairSoft/job/PR-400/1/artifact/logs/Fedora-33/root-configure.log)
⚠ critical:
```
-- Could NOT find Pythia8 (missing: PYTHIA8_INCLUDE_DIR PYTHIA8_LIBRARY) 
-- Pythia8 not found. Switching off pythia8 option
```
```
-- Looking for Python
-- Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found version "3.9.1")
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Python2_INCLUDE_DIRS Python2_LIBRARIES Python2_NumPy_INCLUDE_DIRS Interpreter Development NumPy Development.Module Development.Embed) 
    Reason given by package: 
        Interpreter: Wrong major version for the interpreter "/usr/bin/python"
(...)
-- TMVA: Numpy or Python development package not found for python /usr/bin/python3.9. Switching off tmva-pymva option
(...)
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
(...)
-- Found PythonInterp: /usr/bin/python3.9 (found version "3.9.1") 
```
```
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
```
#fuhlig Do we need Z3 (Is it this https://github.com/Z3Prover/z3?)?

Rest is ⛅, let's improve the CI image
```
-- Looking for ZSTD
-- Could NOT find ZSTD (missing: ZSTD_LIBRARIES ZSTD_INCLUDE_DIR ZSTD_VERSION) 
-- ZSTD not found. Switching on builtin_zstd option
```
```
-- Looking for xxHash
-- Could NOT find xxHash (missing: xxHash_LIBRARY xxHash_INCLUDE_DIR) 
-- xxHash not found. Switching on builtin_xxhash option
```
```
-- Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR) 
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)  
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
```
```
-- Looking for GLEW
-- Could NOT find GLEW (missing: GLEW_INCLUDE_DIRS GLEW_LIBRARIES) 
-- GLEW not found. Switching on builtin_glew option
```
```
-- Looking for gl2ps
-- Could NOT find gl2ps (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- gl2ps not found. Switching on builtin_gl2ps option
```
```
-- Could NOT find FTGL (missing: FTGL_INCLUDE_DIR FTGL_LIBRARY) 
-- ftgl library not found. Set variable FTGL_ROOT_DIR to point to your installation
-- For the time being switching ON 'builtin_ftgl' option
```
```
-- Looking for m
-- Looking for m - not found
```

**Comment by dennisklein** [comment]
## [macOS 11.2 - `root-configure.log`](https://alfa-ci.gsi.de/job/FairRootGroup/job/FairSoft/job/PR-400/1/artifact/logs/macOS-11.2/root-configure.log)
⚠ critical:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
-- OpenSSL not found, switching ON 'builtin_openssl' option.
```
Rest is ⛅, let's improve the CI image
```
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
```
```
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
```
```
-- Looking for m
-- Looking for m - not found
```

**Comment by dennisklein** [comment]
## [macOS 11.2 - `root-configure.log`](https://alfa-ci.gsi.de/job/FairRootGroup/job/FairSoft/job/PR-400/1/artifact/logs/macOS-11.2/root-configure.log)
⚠ critical:
```
-- Looking for Python
-- Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found version "3.8.5")
-- Could NOT find Python2 (missing: Python2_NumPy_INCLUDE_DIRS NumPy) (found version "2.7.18")
(...)
-- TMVA: Numpy or Python development package not found for python /usr/bin/python3.8. Switching off tmva-pymva option
(...)
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
```
Rest is ⛅, let's improve the CI image:
```
-- Looking for PCRE
-- Could NOT find PCRE (missing: PCRE_INCLUDE_DIR PCRE_PCRE_LIBRARY) 
-- PCRE not found. Switching on builtin_pcre option
```
```
-- Looking for LZMA
-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- LZMA not found. Switching on builtin_lzma option
```
```
-- Looking for ZSTD
-- Could NOT find ZSTD (missing: ZSTD_LIBRARIES ZSTD_INCLUDE_DIR ZSTD_VERSION) 
-- ZSTD not found. Switching on builtin_zstd option
```
```
-- Looking for xxHash
-- Could NOT find xxHash (missing: xxHash_LIBRARY xxHash_INCLUDE_DIR) 
-- xxHash not found. Switching on builtin_xxhash option
```
```
-- Looking for LZ4
-- Could NOT find LZ4 (missing: LZ4_LIBRARY LZ4_INCLUDE_DIR) 
-- LZ4 not found. Switching on builtin_lz4 option
```
```
-- Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR) 
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)  
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
```
```
-- Looking for GLEW
-- Could NOT find GLEW (missing: GLEW_INCLUDE_DIRS GLEW_LIBRARIES) 
-- GLEW not found. Switching on builtin_glew option
```
```
-- Looking for gl2ps
-- Could NOT find gl2ps (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- gl2ps not found. Switching on builtin_gl2ps option
```
```
-- Could NOT find GFAL (missing: GFAL_INCLUDE_DIR SRM_IFCE_INCLUDE_DIR GFAL_LIBRARY) 
-- GFAL library not found. Set variable GFAL_DIR to point to your gfal installation
                      and the variable SRM_IFCE_DIR to the srm_ifce installation
-- For the time being switching OFF 'gfal' option
```
```
-- Could NOT find FTGL (missing: FTGL_INCLUDE_DIR FTGL_LIBRARY) 
-- ftgl library not found. Set variable FTGL_ROOT_DIR to point to your installation
-- For the time being switching ON 'builtin_ftgl' option
```
```
-- Looking for TBB
-- Could NOT find TBB (missing: TBB_ROOT_DIR TBB_INCLUDE_DIR TBB_LIBRARY) (Required is at least version "2018")
-- TBB not found, enabling 'builtin_tbb' option
```
```
-- Looking for m
-- Looking for m - not found
```

**Review by dennisklein — CHANGES_REQUESTED** [review]
* Please also bump the version in the `legacy/README.md` file (in the table).
* Please prefix your commit message with `[legacy] `, so we don't get lost in the git history as long as we are maintaining both worlds

Thx, rest looks good, I will merge after this, so we get even more platforms tested (PR CI build is just a short list of system)!

**Comment by dennisklein** [comment]
https://alfa-ci.gsi.de/job/FairRootGroup/job/FairSoft/job/PR-400/1/artifact/logs/Fedora-33/pythia8-install.log
```
bash: rsync: command not found
bash: rsync: command not found
bash: rsync: command not found
bash: rsync: command not found
bash: rsync: command not found
```
Ok, this might explain why root could not find Pythia8.

**Comment by fuhlig1** [comment]
> * Please also bump the version in the `legacy/README.md` file (in the table).
> * Please prefix your commit message with `[legacy] `, so we don't get lost in the git history as long as we are maintaining both worlds

Done.

**Comment by ChristianTackeGSI** [comment]
Could you please `git rebase -i`, use the "reword" function and prefix the commits also with "[legacy]"?

**Comment by fuhlig1** [comment]
@ChristianTackeGSI, should I push to the same pull request or should I open a new one?

**Comment by ChristianTackeGSI** [comment]
After rebase, do a force push to the exact same branch, please. The CI will notice and rebuild.

**Pull request merged**
