### PR TITLE
Bump FairLogger, FairMQ, DDS and dependencies.

### PR DESCRIPTION
**Pull request by kresan**

### CODE REVIEW

**Comment by kresan** [comment]
Was not able to resolve wn_bin error of DDS, although patch from spack version applied. @dennisklein @ChristianTackeGSI could you please have a look?

**Review by ChristianTackeGSI — APPROVED** [review]
Generally looks good to me.

About DDS failing: On which platform?

**Comment by kresan** [comment]
> About DDS failing: On which platform?

macOS 10.15.7
Here is the error message:
```
[100%] Linking CXX executable dds-session
[100%] Built target dds-session
[  4%] Built target dds_user_defaults_lib
[ 10%] Built target dds-user-defaults
[ 40%] Built target dds_topology_lib
[ 78%] Built target dds_protocol_lib
[ 89%] Built target dds_intercom_lib
[ 97%] Built target dds-agent
Scanning dependencies of target wn_bin
[100%] Generate WN binary package
CMake Error at /Users/kresan/SSD2/FairSoft/github/FairSoft_test/legacy/basics/DDS/cmake/DDSCollectWNPkgFiles.cmake:10 (file):
  file Could not resolve file @rpath/libboost_atomic.dylib


make[3]: *** [CMakeFiles/wn_bin] Error 1
make[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2
make[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2
make: *** [wn_bin] Error 2
```

**Comment by ChristianTackeGSI** [comment]
Oh well.

First of all, we are still hoping for https://github.com/FairRootGroup/DDS/issues/304.

Guesses / ideas:
* Can you check, whether the wn_bin binary has a correct RPATH? (spack has a lot of magic to force correct RPATH)
* spack also sets a lot of `LD_LIBRARY_PATH` / `DYLD_FALLBACK_something`. This could also help?

**Pull request merged**
