### PR TITLE
[spack] r3broot: Update no_boost_load.patch

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
R3BRoot moved the file (and changed it a bit).
So we need to update our patch.

Also add a doc string.

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
@kresan 
Could you also comment, whether the no_boost_load patch would be acceptable upstream by now?
As in: Should I file a PR for it?

**Review by kresan — APPROVED** [review]

**Comment by kresan** [comment]
This manual loading of Boost libs has to be removed upstream. I will first try to contact the CALIFA responsible person to do that.

**Comment by kresan** [comment]
Issue created https://github.com/R3BRootGroup/R3BRoot/issues/381

**Comment by ChristianTackeGSI** [comment]
Thanks @kresan for filing the issue! :-)

**Pull request merged**
