### PR TITLE
Backport ROOT_LIBRARY_PATH; Fix Fedora 34 somewhat

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
* This feature got added in ROOT 6.24.
  Let's backport to older ROOT versions.
  See: root-project/root#7031

  Also

  Move a few spack recipes over to use the new env var.
  
* Backport some fixes to get Fedora 34 compiling most, except nov20 and jun19.

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
Pinging @dennisklein:
* If this looks good enough, I would try to create a PR on upstream ROOT with this. Hopefully, this will give us better discussions upstream.
* If this looks good, I would also try to get this into `patch()` into upstream spack.
* Could you ping anyone relevant, please?

**Comment by ChristianTackeGSI** [comment]
CI will likely fail due to #355 missing. Let's see.

**Comment by ChristianTackeGSI** [comment]
@dennisklein and I had s discussion.
Result:
* I will rsearch, whether the rootrc mechanism could be used without interference by `$HOME/.rootrc` (I currently assume, that there is interference)
* If this turns out to interfere, I will try to upstream the patch to ROOT. Especially to start a better discussion there.
* I would like to keep this PR open as a reminder, until the upstream discussion stabilizes.

**Comment by ChristianTackeGSI** [comment]
Looks like the local `.rootrc` overrides the `system.rootrc` completely:

```console
$ export FOO=/foo
$ export BAR=/bar
$ egrep '(FOO|BAR)' /opt/spack/install-tree/debian10/gcc-8.3.0/root-6.22.06-lmit7/etc/system.rootrc
Unix.*.Root.DynamicPath:    $(FOO):/usr/local/lib/rootstuff
$ egrep '(FOO|BAR)' ~/.rootrc
Unix.*.Root.DynamicPath: $(BAR):/home/my-root-stuff/lib
$ /opt/spack/install-tree/debian10/gcc-8.3.0/root-6.22.06-lmit7/bin/root.exe -l
root [0] gSystem->GetDynamicPath()
(const char *) "/bar:/home/my-root-stuff/lib:/opt/spack/install-tree/debian10/gcc-8.3.0/root-6.22.06-lmit7/lib:"
root [1] 
$ rm ~/.rootrc
$ /opt/spack/install-tree/debian10/gcc-8.3.0/root-6.22.06-lmit7/bin/root.exe -l
root [0] gSystem->GetDynamicPath()
(const char *) "/foo:/usr/local/lib/rootstuff:/opt/spack/install-tree/debian10/gcc-8.3.0/root-6.22.06-lmit7/lib:"
```

**Comment by ChristianTackeGSI** [comment]
Upstream PR: https://github.com/root-project/root/pull/7031

marked this PR as "postponed", until we get some feeback upstream.

**Comment by ChristianTackeGSI** [comment]
PR updated to use the official patch from ROOT upstream.

Also cherry-picked a checksum fix from #399, so that this thing should run green. So whichever PR gets merged later might need a rebase (hopefully automatic).

**Review by dennisklein — APPROVED** [review]

**Review by dennisklein — APPROVED** [review]

**Pull request merged**
