### PR TITLE
Add initial versions of jun19 and dev environments.

### PR DESCRIPTION
**Pull request by kresan**

### CODE REVIEW

**Comment by fuhlig1** [comment]
Can you please update the README sucht that people know how to use the environments.

**Comment by dennisklein** [comment]
FYI: I have added a [github check WIP](https://github.com/apps/wip)

**Comment by ChristianTackeGSI** [comment]
Why a specific version of cmake?
Especially, why in the "dev" editions?

**Comment by kresan** [comment]
@fuhlig1 The README is now updated

**Comment by kresan** [comment]
@ChristianTackeGSI  This version of cmake was in jun19 release of old FairSoft.
Currently the dev environments are just an example, where I focused on how to deal with specs (+x +opengl). I had no intention to fix cmake version

**Pull request merged**
