### PR TITLE
[spack] root related things

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
* Add 6.22.x
* cleanup
* improve `meas~llvm` handling in our environments.

### CODE REVIEW

**Comment by dennisklein** [comment]
@kresan Can you comment on why we use `mesa~llvm` explicitely? Was it just a concretizer hint or is there some deeper reason for this variant choice?

**Comment by fuhlig1** [comment]
Hi @dennisklein,

maybe I can comment. mesa has some llvm backend which brings in tons of additional dependencies. This slows done the compilation enormously and I haven't seen that it is needed anywhere. So I decided long time ago to switch it off. If I remember correctly I checked at that time and none of the packages from any package manager were providing this back end. This has maybe changed meanwhile and we can debate the previous decision.

**Comment by kresan** [comment]
It was a concretizer hint. ROOT depends on gl and glu. For linux systems mesa is used as a provider for gl. In its turn mesa has a llvm variant, which turns on llvm support and dependency and is on by default. We do not need this part.

**Comment by dennisklein** [comment]
@kresan @fuhlig1 Thx for the context, so I conclude we still want to disable the llvm variant because it causes significant unnecessary compile times.

**Review by dennisklein — APPROVED** [review]

**Comment by ChristianTackeGSI** [comment]
> […] If I remember correctly I checked at that time and none of the packages from any package manager were providing this back end. This has maybe changed meanwhile and we can debate the previous decision.

Just for informaation, Debian has it:
```console
root@citpc008:~# aptitude why libllvm7 | grep llvm
i A libgl1-mesa-dri Depends libllvm7 (>= 1:7~svn298832-1~)
```

**Pull request merged**
