### PR TITLE
Fix issues with jan24

### PR DESCRIPTION
**Pull request by fuhlig1**
This MR fixes the problem with crashes due to reapplying patches when rerunning the build.
Also add protobuf development package in setup scripts where it was missing.

### CODE REVIEW

**Comment by fuhlig1** [comment]
The MR should be ported to jan24_patches.

**Review by dennisklein — APPROVED** [review]

**Comment by fuhlig1** [comment]
@dennisklein,

in my opinion the PR is now okay. Could you please confirm and merge it. After merging the commits should be ported to the jan24_patches branch such that a first patch release jan24p1 can be created.

**Review by dennisklein — COMMENTED** [review]
:+1:, took the liberty to add the following for consistency
```diff
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -570,9 +570,9 @@ if(packages)
       else()
         set(comment "single-threaded (change with ${BMagenta}-DGEANT4MT=ON${CR})")
       endif()
-    elseif(dep STREQUAL dds OR dep STREQUAL onnxruntime)
+    elseif(dep STREQUAL onnxruntime)
       set(version_str "${${dep}_version}")
-      set(comment "optional (by building target ${BMagenta}${dep}${CR} explicitely)")
+      set(comment "optional (by building target ${BMagenta}onnxruntime${CR} explicitely)")
     else()
       set(version_str "${${dep}_version}")
     endif()
```

**Comment by dennisklein** [comment]
backported to `jan24_patches` as well

**Pull request merged**
