### PR TITLE
Hint `ICU_ROOT/lib` to DDS

### PR DESCRIPTION
**Pull request by dennisklein**
@fuhlig1 Let me know, if this resolves your build issue with the `wn_bin` target of DDS.

### CODE REVIEW

**Review by fuhlig1 — APPROVED** [review]
Works for me.

**Comment by ChristianTackeGSI** [comment]
Two questions:

1. Should we try to get this patch merged into DDS upstream?

2. Shizld we add that patch to the spack packaging? (desipute not being needed there)

**Comment by karabowi** [comment]
On my mac (11.6) I had the same ICU problem. This patch fixed the DDS build for me as well.

**Comment by fuhlig1** [comment]
we should propose the patch to Anar.

**Comment by dennisklein** [comment]
If anyone is making PRs, consider to propose both patches from https://github.com/FairRootGroup/FairSoft/tree/dev/legacy/dds

**Comment by ChristianTackeGSI** [comment]
* `fix_boost_lookup.patch` – looks like it already is in this commit: 
  https://github.com/FairRootGroup/DDS/commit/8c6c950ed013da570da2120f03c484cb62fb6014
* `allow_dds_ld_library_path_as_cmake_var.patch` – PR here:
  https://github.com/FairRootGroup/DDS/pull/438

**Pull request merged**
