### PR TITLE
[spack] Bump clhep@2.4.4.0, geant4@10.7, geant4-vmc@5-3

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
- [X] (needed) #356  for the legacy version of this PR.

Also a fix for geant3@2.7 on macos11 is included.

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
* Linux: Only workflow-dev fails (maybe we should mark it might-fail?)
* @dennisklein could you take a look at the geant3 part? The rest is pretty standard.

**Comment by dennisklein** [comment]
> @dennisklein could you take a look at the geant3 part?

Does it need 11 in all cases for version 2.7? If not what does it depend on, the ROOT cxx standard?

**Comment by ChristianTackeGSI** [comment]
As far as I understood it:
* cmake in geant3 2.7 does not set a default CXX version
* apple clang defaults to C++98 in that case
* geant3 includes ROOT includes
* ROOT (6.16 in this case, because it's jun19) requires at least C++11 and checks for thits.

Options I can see:
* Drop jun19 (which is IMHO okay: spack is still "experimental", so we're allowed to drop things).
  In this case I would ask @kresan to upgrade the r3broot env to something like nov20, if that's possible.
* Narrow down this workaround to something like `.satisfies('@2.7 %apple-clang@??')`
* Maybe we should bind more closely to ROOT's CXX-level?
  `for level in cxxlevels: depends_on('root cxxstd=' + level, when='cxxstd=' + level)`
  But as far as I understood the CXX levels, they're basically "mix and match", as long, as you use the same compiler. So I doubt this is really needed.
* Keep my current hacky workaround

I am undecided.

**Comment by dennisklein** [comment]
Which error did you get?

**Comment by ChristianTackeGSI** [comment]
A bunch of errors, most notably:
```console
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/test_workdir/stage/spack-stage-geant3-2.7-ymjep4xphuxdr3hmnkj44jy443rfkkno/spack-src/TGeant3/TGeant3f77.cxx:25:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/test_workdir/stage/spack-stage-geant3-2.7-ymjep4xphuxdr3hmnkj44jy443rfkkno/spack-src/TGeant3/TGeant3f77.h:9:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/test_workdir/stage/spack-stage-geant3-2.7-ymjep4xphuxdr3hmnkj44jy443rfkkno/spack-src/TGeant3/TGeant3.h:21:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/TVirtualMC.h:24:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/TMCProcess.h:18:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/Rtypes.h:23:
In file included from /Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/RtypesCore.h:23:
/Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/ROOT/RConfig.h:48:4: error: "ROOT requires support for C++11 or higher."
#  error "ROOT requires support for C++11 or higher."
   ^
/Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/ROOT/RConfig.h:50:5: error: "Pass `-std=c++11` as compiler argument."
#   error "Pass `-std=c++11` as compiler argument."
    ^
```

But also things like:
```console
/Users/alfaci/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/install-tree/darwin-bigsur-x86_64/apple-clang-12.0.0/root-6.16.00-6yc76syewvo7ajz254wr6n3hptxf6xa6/include/ROOT/span.hxx:50:36: error: a space is required between consecutive right angle brackets (use '> >')
struct is_array_class<std::vector<T>> {
                                   ^~
                                   > >
```

For more, see:
`witmac007: ~/alfaci/workspace/FairRootGroup_FairSoft_PR-355/build/stage/spack-stage-geant3-2.7-ymjep4xphuxdr3hmnkj44jy443rfkkno/spack-build-out.txt`

**Comment by dennisklein** [comment]
Thanks for the details, in that case I like your proposed solution. (I was asking myself, if a hard-coded `11` on the geant3 package level would be too specific)

**Review by dennisklein — APPROVED** [review]

**Pull request merged**
