### PR TITLE
Cleanup packages

### PR DESCRIPTION
**Pull request by dennisklein**
* Delete
  * `fairsoft.geant4`
  * `fairsoft.geant4-data`
  * `fairsoft.g4*`
  * `fairsoft.vc`
  * `fairsoft.perl-datemanip`
  * `fairsoft.grpc`
  * `fairsoft-backports.cmake`
  * `fairsoft-backports.openblas`

* Move
  * `fairsoft.hepmc` -> `fairsoft-backports.hepmc`
  * `fairsoft.msgpack-c` -> `fairsoft-backports.msgpack-c`

### CODE REVIEW

**Comment by dennisklein** [comment]
@kresan @ChristianTackeGSI AFAICS we didn't have any changes in the geant4 packages, correct me, if I overlooked anything.

**Comment by ChristianTackeGSI** [comment]
For `g4*` I am quite sure, that we were very close to upstream spack. I remember doing something there

For `geant4*` upstream changed the version numbering at one place. And I don't know, if they have the exact same versions that we have.

I was planning to look into that deeper later on. Dima might now better.

**Review by kresan — APPROVED** [review]
I do not recall something special about geant4. Since we anyhow need to do quantitative tests with 10.6, then let's try to do that with the upstream one.

**Comment by dennisklein** [comment]
> Since we anyhow need to do quantitative tests with 10.6,

Shall I also bump from `10.6.0` to `10.6.2` then?

**Comment by kresan** [comment]
> Shall I also bump from `10.6.0` to `10.6.2` then?

Latest geant4_vmc should work with geant4 10.6.2 as well. So let's try it.

**Comment by dennisklein** [comment]
https://cdash.gsi.de/testDetails.php?test=7202188&build=247614 is fixed upstream https://github.com/abseil/abseil-cpp/pull/670 and already packaged in spack develop: https://github.com/spack/spack/pull/17383. Will do a backport.

**Comment by dennisklein** [comment]
https://cdash.gsi.de/testDetails.php?test=7201457&build=247599 is somehow because of the external-only clhep dependency of the upstream geant4 package. Investigating.

**Comment by dennisklein** [comment]
Still investigating my fix https://github.com/FairRootGroup/FairSoft/pull/323/commits/608d67fe7d6318438fcf213575fe896a638a5292. It may be restricted to Geant4 10.5 still ...testing

**Comment by dennisklein** [comment]
The FairRoot Geant4 with external CLHEP is proposed upstream: https://github.com/FairRootGroup/FairRoot/pull/1015

**Pull request merged**
