### PR TITLE
Fix ICU version check, rootconfig.sh OPENGL_gl_LIBRARY

### PR DESCRIPTION
**Pull request by klenze**
If one installs ICU 63.1 (package_versions.sh), then one should not expect ICU 53.1 to be installed afterwards.

### CODE REVIEW

**Comment by fuhlig1** [comment]
Why do you need the fix? Are you building FairSoft on Linux with Clang?

**Comment by klenze** [comment]
Yes, unfortunately. then I tried to compile root with clang9 on linux and could not get it to work, so this is probably moot now.

**Comment by kresan** [comment]
Is it still an open issue @klenze ?
Meanwhile we migrate to the new build system - based on Spack. You can find it in the dev branch. Versions of jun19 are also available there - in env/jun19/* environments. Can you test if it solves your problem?

**Comment by kresan** [comment]
There is no further patch release for jun19 planned. Closing this. Please use FairSoft based on Spack from the dev branch.

**Pull request closed without merging**
