### PR TITLE
[legacy] Geant4 10.7.0, CLHEP 2.4.4.0, and Geant4VMC 5.3

### PR DESCRIPTION
**Pull request by dennisklein**

### CODE REVIEW

**Review by ChristianTackeGSI — APPROVED** [review]
Looks good.

**Comment by ChristianTackeGSI** [comment]
Do you want to bump dds and/or boost in this PR as well?

**Comment by dennisklein** [comment]
> Do you want to bump dds and/or boost in this PR as well?

Hm, let's do this in a separate step.

**Comment by dennisklein** [comment]
ROOT 6.22.06 has problems on our macOS test systems, so not bumping ROOT for now.

**Pull request merged**
